In [3]:
import pandas as pd

populacja = pd.read_csv("populacja_stanow.csv")
skroty = pd.read_csv("skroty_stanow.csv")
dane = pd.read_csv("police.csv")
df = pd.merge(populacja, skroty, on='state', how='inner')
dane = dane.rename(columns={'state': 'abbreviation'})
dane1=dane['abbreviation'].value_counts()
df1 = df.merge(dane1, on='abbreviation', how='left')
df1['incidents_per_1000'] = df1['count'] / df1['population'] * 1000
df1

             state  population abbreviation  count  incidents_per_1000
0          Alabama     5024279           AL    104            0.020699
1           Alaska      733391           AK     39            0.053178
2          Arizona     7151502           AZ    254            0.035517
3         Arkansas     3011524           AR     83            0.027561
4       California    39538223           CA    799            0.020208
5         Colorado     5773714           CO    195            0.033774
6      Connecticut     3605944           CT     21            0.005824
7         Delaware      989948           DE     13            0.013132
8          Florida    21538187           FL    350            0.016250
9          Georgia    10711908           GA    182            0.016990
10          Hawaii     1455271           HI     30            0.020615
11           Idaho     1839106           ID     42            0.022837
12        Illinois    12812508           IL    104            0.008117
13         Indiana     6785528           IN     95            0.014000
14            Iowa     3190369           IA     32            0.010030
15          Kansas     2937880           KS     50            0.017019
16        Kentucky     4505836           KY     95            0.021084
17       Louisiana     4657757           LA    109            0.023402
18           Maine     1362359           ME     22            0.016148
19        Maryland     6177224           MD     79            0.012789
20   Massachusetts     7029917           MA     35            0.004979
21        Michigan    10077331           MI     78            0.007740
22       Minnesota     5706494           MN     61            0.010690
23     Mississippi     2961279           MS     65            0.021950
24        Missouri     6154913           MO    141            0.022909
25         Montana     1084225           MT     31            0.028592
26        Nebraska     1961504           NE     24            0.012236
27          Nevada     3104614           NV     96            0.030922
28   New Hampshire     1377529           NH     13            0.009437
29      New Jersey     9288994           NJ     68            0.007320
30      New Mexico     2117522           NM    106            0.050059
31        New York    20201249           NY    101            0.005000
32  North Carolina    10439388           NC    156            0.014943
33    North Dakota      779094           ND     11            0.014119
34            Ohio    11799448           OH    155            0.013136
35        Oklahoma     3959353           OK    164            0.041421
36          Oregon     4237256           OR     88            0.020768
37    Pennsylvania    13002700           PA    108            0.008306
38    Rhode Island     1097379           RI      4            0.003645
39  South Carolina     5118425           SC     88            0.017193
40    South Dakota      886667           SD     17            0.019173
41       Tennessee     6910840           TN    139            0.020113
42           Texas    29145505           TX    481            0.016503
43            Utah     3271616           UT     60            0.018340
44         Vermont      643077           VT      9            0.013995
45        Virginia     8631393           VA     95            0.011006
46      Washington     7705281           WA    152            0.019727
47   West Virginia     1793716           WV     54            0.030105
48       Wisconsin     5893718           WI     91            0.015440
49         Wyoming      576851           WY     14            0.024270